name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  API_KEY: ${{vars.OPENWEATHER_API_KEY}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    #env:
      #API_KEY: ${{secrets.OPENWEATHER_API_KEY}}
      #API_KEY: ${{vars.OPENWEATHER_API_KEY}}
    steps:
      - name: Echo key.
        run: echo API_KEY=${{env.API_KEY}} > ./.env 

      - name: Log key.
        run: cat .env
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.9.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_KEY }}
          publish_dir: ./dist
